# Generated by Django 3.2.3 on 2021-05-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'CTA',
                'verbose_name_plural': 'CTAs',
            },
        ),
        migrations.AlterModelOptions(
            name='contentforkar1',
            options={'verbose_name': 'Content For Kar1', 'verbose_name_plural': 'Contents For Kar1'},
        ),
        migrations.AlterModelOptions(
            name='contentforkar2',
            options={'verbose_name': 'Content For Kar2', 'verbose_name_plural': 'Contents For Kar2'},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Title', 'verbose_name_plural': 'Titles'},
        ),
        migrations.RenameField(
            model_name='features',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='title',
            name='features',
            field=models.ManyToManyField(to='tindog_app.Features'),
        ),
    ]
