# Generated by Django 3.2.3 on 2021-05-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tindog_app', '0002_auto_20210531_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentForKar1',
            new_name='ContentsForKar',
        ),
        migrations.DeleteModel(
            name='ContentForKar2',
        ),
        migrations.AlterModelOptions(
            name='contentsforkar',
            options={'verbose_name': 'Content For Kar', 'verbose_name_plural': 'Contents For Kar'},
        ),
    ]
